import type { RoadIssue, User, DashboardStats } from "./types";

export const mockUser: User = {
  id: "1",
  name: "John Engineer",
  role: "admin",
};

export const mockFieldOfficers: User[] = [
  { id: "2", name: "Sarah Johnson", role: "field-officer" },
  { id: "3", name: "Michael Chen", role: "field-officer" },
  { id: "4", name: "Emily Davis", role: "field-officer" },
  { id: "5", name: "Robert Wilson", role: "field-officer" },
];

export const mockIssues: RoadIssue[] = [
  {
    id: "ISS-001",
    roadName: "Main Street",
    location: "Between Oak Ave and Pine St",
    issueType: "pothole",
    severity: "high",
    status: "in-progress",
    source: "field-officer",
    reportedDate: "2026-01-15",
    assignedOfficer: "Sarah Johnson",
    description: "Large pothole approximately 2 feet in diameter",
  },
  {
    id: "ISS-002",
    roadName: "Highway 101",
    location: "Mile marker 45",
    issueType: "cracks",
    severity: "medium",
    status: "reported",
    source: "field-officer",
    reportedDate: "2026-01-18",
    description: "Multiple cracks spanning 50 feet",
  },
  {
    id: "ISS-003",
    roadName: "Elm Boulevard",
    location: "Near City Hall",
    issueType: "drainage",
    severity: "critical",
    status: "in-progress",
    source: "civilian",
    reportedDate: "2026-01-20",
    assignedOfficer: "Michael Chen",
    description: "Blocked drainage causing flooding during rain",
  },
  {
    id: "ISS-004",
    roadName: "Cedar Lane",
    location: "Intersection with Maple Drive",
    issueType: "signage",
    status: "unverified",
    source: "civilian",
    reportedDate: "2026-01-22",
    description: "Stop sign damaged and barely visible",
  },
  {
    id: "ISS-005",
    roadName: "Park Avenue",
    location: "Between 5th and 6th Street",
    issueType: "pothole",
    severity: "low",
    status: "completed",
    source: "field-officer",
    reportedDate: "2026-01-10",
    assignedOfficer: "Emily Davis",
    description: "Small pothole repaired",
  },
  {
    id: "ISS-006",
    roadName: "River Road",
    location: "Near the bridge",
    issueType: "cracks",
    status: "unverified",
    source: "civilian",
    reportedDate: "2026-01-25",
    description: "Surface cracks reported by local resident",
  },
  {
    id: "ISS-007",
    roadName: "Industrial Way",
    location: "Warehouse district entrance",
    issueType: "pothole",
    severity: "high",
    status: "reported",
    source: "field-officer",
    reportedDate: "2026-01-24",
    description: "Multiple potholes affecting truck traffic",
  },
  {
    id: "ISS-008",
    roadName: "School Street",
    location: "In front of Lincoln Elementary",
    issueType: "signage",
    severity: "critical",
    status: "in-progress",
    source: "field-officer",
    reportedDate: "2026-01-21",
    assignedOfficer: "Robert Wilson",
    description: "Crosswalk signs need immediate replacement",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalIssues: mockIssues.length,
  reported: mockIssues.filter((i) => i.status === "reported").length,
  inProgress: mockIssues.filter((i) => i.status === "in-progress").length,
  completed: mockIssues.filter((i) => i.status === "completed").length,
  unverified: mockIssues.filter((i) => i.status === "unverified").length,
};
